apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  ignoreDifferences:
    - kind: Secret
      name: test-secret
      namespace: myapp
      jsonPointers:
        - /data
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
